--- 

name: "firstworkflow with devops class" 

on: 

push: 

   branches: 

     - main 
     - master

jobs: 

  first-job: 

    runs-on: ubuntu-latest 

    steps: 

      - name: Checking out to a repository 

        uses: actions/checkout@v4 

      - name: Printing the content of the file 

        run: echo "hello world" 
... 
